"""
Backtest Database Models

Objective:
----------
Keep the token_positions table minimal and store the entire state of each token in a single JSONB column.
We've removed the old per-token columns (block_number, symbol, etc.), and rely solely on 'token_position'.

Algorithmic Steps:
------------------
1. A StrategyRun is defined to track high-level strategy metadata.
2. A TokenPosition table references a run via strategy_run_id. 
3. The token_address provides a quick lookup per token, and 'token_position' (JSONB) holds the complete
   TokenPosition data (static + dynamic) generated by TokenPosition.to_full_dict().
"""

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, JSON, DateTime
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy import ForeignKey

Base = declarative_base()

class StrategyRun(Base):
    """Tracks strategy configuration and metadata"""
    __tablename__ = 'strategy_runs'
    
    id = Column(Integer, primary_key=True)
    name = Column(String)
    parameters = Column(JSON)
    start_block = Column(Integer)
    end_block = Column(Integer)
    created_at = Column(DateTime) 


class TokenPosition(Base):
    """Tracks each token position as a JSONB object"""
    __tablename__ = 'token_positions'
    
    id = Column(Integer, primary_key=True)
    strategy_run_id = Column(Integer, ForeignKey('strategy_runs.id'))
    token_address = Column(String)
    token_position = Column(JSONB, nullable=True)
