[package]
name = "eth_alpha_lab"
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"
workspace = "../.."

[dependencies]
clap = { version = "4.5", features = ["derive"] }
eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio-native-tls", "postgres", "json"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toml.workspace = true
