-- Risk Atlas observation rows for a single run/protocol.
-- Keep selected columns as-of only; labels are joined separately.
SELECT
    o.run_id,
    lower(o.token_address) AS token_address,
    lower(o.pool_address) AS pool_address,
    o.protocol,
    o.block_number,
    o.timestamp,
    o.active_observation_index,
    o.active_reasons,
    o.tx_count,
    o.token_transfer_count,
    o.denom_transfer_count,
    o.buy_volume_denom,
    o.sell_volume_denom,
    o.total_bribe_eth,
    o.total_liquidity_denom,
    o.denom_reserve,
    o.token_reserve,
    o.price_to_initial_ratio,
    o.price_denom_per_token,
    o.initial_price_denom_per_token,
    o.buy_tax,
    o.sell_tax,
    o.can_buy,
    o.can_sell,
    o.effective_can_buy,
    o.effective_can_sell,
    o.liquidity_removed_as_of,
    o.liquidity_removal_in_block,
    o.direct_lp_removal_as_of,
    o.direct_lp_removal_in_block,
    o.lp_approved_pct_as_of,
    o.lp_approval_count_in_block,
    o.lp_approval_seen_as_of,
    o.lp_total_supply,
    o.lp_max_approval_amount_as_of,
    o.lp_max_approval_pct_as_of,
    o.lp_removable_pct_as_of,
    o.lp_router_removable_pct_as_of,
    o.lp_approval_owner_is_creator,
    o.creator_lp_balance_pct_as_of,
    o.creator_lp_approved_pct_as_of,
    o.creator_lp_removable_pct_as_of,
    o.creator_lp_router_removable_pct_as_of,
    o.creator_lp_approved_gt_90_pct_as_of,
    o.creator_lp_router_removable_gt_90_pct_as_of,
    o.last_lp_approval_amount_pct_of_total_supply,
    o.first_lp_approval_to_as_of_chain_block_delta,
    o.last_lp_approval_to_as_of_chain_block_delta,
    o.pool_creation_to_first_lp_approval_chain_block_delta,
    o.pool_creation_to_last_lp_approval_chain_block_delta,
    o.trading_enabled_to_first_lp_approval_chain_block_delta,
    o.trading_enabled_to_last_lp_approval_chain_block_delta,
    o.control_transfer_from_after_renounce_seen_as_of,
    o.control_transfer_from_after_renounce_in_block,
    o.control_transfer_from_holder_to_burn_seen_as_of,
    o.control_transfer_from_holder_to_burn_in_block,
    o.control_transfer_from_pair_seen_as_of,
    o.control_transfer_from_pair_in_block,
    o.control_transfer_from_without_transfer_log_seen_as_of,
    o.control_transfer_from_without_transfer_log_in_block,
    o.pair_token_to_control_seen_as_of,
    o.pair_token_to_control_in_block,
    o.pair_token_to_control_to_pool_reserve_ratio,
    o.pair_balance_backdoor_signal_seen_as_of,
    o.pair_balance_backdoor_signal_in_block,
    o.last_pair_balance_backdoor_signal_to_as_of_chain_block_delta,
    o.token_transfer_to_total_supply_ratio,
    o.token_transfer_to_pool_token_reserve_ratio
FROM public.risk_atlas_observations o
JOIN public.risk_atlas_pool_eligibility e
  ON e.run_id = o.run_id
 AND lower(e.token_address) = lower(o.token_address)
 AND lower(e.pool_address) = lower(o.pool_address)
WHERE o.run_id = %(run_id)s
  AND e.eligible
  AND UPPER(COALESCE(e.protocol, o.protocol, '')) = %(protocol)s;
