#!/usr/bin/env python3
"""
TRANSACTION TIMING ANALYSIS SYSTEM

OBJECTIVE: Measure and analyze the complete transaction processing pipeline from 
mempool arrival to final processing completion, identifying bottlenecks and 
performance characteristics.

ALGORITHMIC DESCRIPTION:
1. Load transaction timing data from CSV logs generated by Rust scam detection service
2. Parse timing measurements for each transaction phase:
   - Mempool residence time (external network delay)
   - Internal queue time (our system delay)
   - Pool address lookup time (database query)
   - REVM simulation time (EVM execution)
   - State analysis time (diff calculation)
   - Scam detection time (ML inference)
3. Calculate statistical distributions and performance metrics
4. Identify performance categories and SLA compliance
5. Generate comprehensive timing breakdown analysis

MEASUREMENT POINTS (mapped to Rust code):
- mempool_arrival_timestamp_ms: When tx first detected in mempool
- queue_entry_timestamp_ms: When tx enters our processing queue  
- processing_start_timestamp_ms: When we begin processing
- pool_check_start/end_timestamp_ms: Pool address lookup phase
- revm_simulation_start/end_timestamp_ms: REVM EVM simulation phase
- state_analysis_start/end_timestamp_ms: State diff calculation phase
- scam_detection_start/end_timestamp_ms: ML scam detection phase
- processing_end_timestamp_ms: Complete processing finished

DURATION CALCULATIONS (all in microseconds for precision):
- mempool_residence_time_us: Time in public mempool before we detect it
- internal_queue_time_us: Time waiting in our processing queue
- pool_check_time_us: Time spent checking if transaction involves known pools
- revm_simulation_time_us: Time spent in REVM EVM simulation
- state_analysis_time_us: Time spent calculating state changes
- scam_detection_time_us: Time spent in scam detection algorithms
- total_processing_time_us: Sum of all our internal processing phases
- end_to_end_time_us: Total time from mempool arrival to completion

CODE REFERENCES:
- Timing struct definition: rust/mempool_processor/src/bin/scam_detection_service.rs:134-211
- Timing measurement points: rust/mempool_processor/src/bin/scam_detection_service.rs:1349-1385
- CSV logging format: rust/mempool_processor/src/bin/scam_detection_service.rs:510-587
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import sys
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Set up plotting style
plt.style.use('seaborn-v0_8')
sns.set_palette("husl")

def load_timing_data(csv_path):
    """
    Load transaction timing data from CSV file generated by Rust service.
    
    CSV Format (from scam_detection_service.rs:510-587):
    tx_hash,mempool_arrival_timestamp_ms,queue_entry_timestamp_ms,processing_start_timestamp_ms,
    pool_check_start_timestamp_ms,pool_check_end_timestamp_ms,revm_simulation_start_timestamp_ms,
    revm_simulation_end_timestamp_ms,state_analysis_start_timestamp_ms,state_analysis_end_timestamp_ms,
    scam_detection_start_timestamp_ms,scam_detection_end_timestamp_ms,processing_end_timestamp_ms,
    internal_queue_time_us,mempool_residence_time_us,pool_check_time_us,revm_simulation_time_us,
    state_analysis_time_us,scam_detection_time_us,total_processing_time_us,end_to_end_time_us,
    is_pool_transaction,pool_address,scam_detected,tx_value_wei,gas_price_wei,gas_limit,
    simulation_successful,affected_accounts_count,sla_violation,performance_category
    """
    try:
        df = pd.read_csv(csv_path)
        print(f"✅ Loaded {len(df):,} transaction timing records from {csv_path}")
        return df
    except FileNotFoundError:
        print(f"❌ Error: Could not find timing data file: {csv_path}")
        print("   Make sure the Rust scam detection service has been running and generating logs.")
        return None
    except Exception as e:
        print(f"❌ Error loading timing data: {e}")
        return None

def analyze_timing_phases(df):
    """
    Analyze each timing phase of transaction processing.
    
    Maps to Rust timing measurements:
    - mempool_residence_time_us: Time before we detect transaction (external)
    - internal_queue_time_us: Time waiting in our queue (internal bottleneck)
    - pool_check_time_us: Database lookup time (internal processing)
    - revm_simulation_time_us: EVM simulation time (core processing)
    - state_analysis_time_us: State diff calculation (post-processing)
    - scam_detection_time_us: ML inference time (final processing)
    """
    print("\n" + "="*80)
    print("TRANSACTION TIMING PHASE ANALYSIS")
    print("="*80)
    
    # Convert microseconds to milliseconds for readability
    timing_phases = {
        'Mempool Residence': 'mempool_residence_time_us',
        'Internal Queue': 'internal_queue_time_us', 
        'Pool Check': 'pool_check_time_us',
        'REVM Simulation': 'revm_simulation_time_us',
        'State Analysis': 'state_analysis_time_us',
        'Scam Detection': 'scam_detection_time_us',
        'Total Processing': 'total_processing_time_us',
        'End-to-End': 'end_to_end_time_us'
    }
    
    results = {}
    
    for phase_name, column in timing_phases.items():
        if column in df.columns:
            data_ms = df[column] / 1000.0  # Convert μs to ms
            
            results[phase_name] = {
                'mean_ms': data_ms.mean(),
                'median_ms': data_ms.median(),
                'p95_ms': data_ms.quantile(0.95),
                'p99_ms': data_ms.quantile(0.99),
                'max_ms': data_ms.max(),
                'std_ms': data_ms.std(),
                'count': len(data_ms[data_ms > 0])  # Non-zero measurements
            }
            
            print(f"\n📊 {phase_name.upper()} TIMING:")
            print(f"   Mean:   {results[phase_name]['mean_ms']:.3f}ms")
            print(f"   Median: {results[phase_name]['median_ms']:.3f}ms") 
            print(f"   P95:    {results[phase_name]['p95_ms']:.3f}ms")
            print(f"   P99:    {results[phase_name]['p99_ms']:.3f}ms")
            print(f"   Max:    {results[phase_name]['max_ms']:.3f}ms")
            print(f"   StdDev: {results[phase_name]['std_ms']:.3f}ms")
            print(f"   Samples: {results[phase_name]['count']:,}")
    
    return results

def analyze_transaction_categories(df):
    """
    Analyze transaction categories based on processing characteristics.
    
    Categories defined in Rust code (scam_detection_service.rs:337-356):
    - Direct-to-miner: 0ms mempool residence (private channels)
    - Pool transactions: Involve known liquidity pools
    - Scam transactions: Detected by ML algorithms
    - Performance categories: excellent/good/acceptable/poor
    """
    print("\n" + "="*80)
    print("TRANSACTION CATEGORY ANALYSIS")
    print("="*80)
    
    total_transactions = len(df)
    
    # Direct-to-miner transactions (0ms mempool residence)
    direct_to_miner = df[df['mempool_residence_time_us'] == 0]
    print(f"\n🚀 DIRECT-TO-MINER TRANSACTIONS:")
    print(f"   Count: {len(direct_to_miner):,} ({len(direct_to_miner)/total_transactions*100:.2f}%)")
    print(f"   These bypass public mempool entirely via private channels (MEV, Flashbots)")
    
    # Pool transactions
    pool_transactions = df[df['is_pool_transaction'] == True]
    print(f"\n🏊 POOL TRANSACTIONS:")
    print(f"   Count: {len(pool_transactions):,} ({len(pool_transactions)/total_transactions*100:.2f}%)")
    print(f"   These interact with known liquidity pools")
    
    # Scam transactions
    scam_transactions = df[df['scam_detected'] == True]
    print(f"\n🚨 SCAM TRANSACTIONS:")
    print(f"   Count: {len(scam_transactions):,} ({len(scam_transactions)/total_transactions*100:.2f}%)")
    print(f"   Detected by ML scam detection algorithms")
    
    # Performance categories
    print(f"\n⚡ PERFORMANCE CATEGORIES:")
    performance_counts = df['performance_category'].value_counts()
    for category, count in performance_counts.items():
        percentage = count / total_transactions * 100
        print(f"   {category.capitalize()}: {count:,} ({percentage:.1f}%)")
    
    # SLA violations
    sla_violations = df[df['sla_violation'] == True]
    print(f"\n⏰ SLA COMPLIANCE:")
    print(f"   Violations: {len(sla_violations):,} ({len(sla_violations)/total_transactions*100:.2f}%)")
    print(f"   Compliance: {(total_transactions-len(sla_violations))/total_transactions*100:.1f}%")

def analyze_bottlenecks(df):
    """
    Identify system bottlenecks by comparing timing phases.
    
    Bottleneck hierarchy analysis based on latency contribution:
    1. External: Mempool residence (network constraint)
    2. Internal: Queue time (system constraint) 
    3. Processing: REVM simulation (computational constraint)
    4. Overhead: Pool checks, state analysis, scam detection
    """
    print("\n" + "="*80)
    print("BOTTLENECK ANALYSIS")
    print("="*80)
    
    # Calculate average contribution of each phase to total latency
    phases = {
        'Mempool Residence': df['mempool_residence_time_us'].mean() / 1000,
        'Internal Queue': df['internal_queue_time_us'].mean() / 1000,
        'Pool Check': df['pool_check_time_us'].mean() / 1000,
        'REVM Simulation': df['revm_simulation_time_us'].mean() / 1000,
        'State Analysis': df['state_analysis_time_us'].mean() / 1000,
        'Scam Detection': df['scam_detection_time_us'].mean() / 1000
    }
    
    total_avg_time = sum(phases.values())
    
    print(f"\n📊 LATENCY CONTRIBUTION BREAKDOWN:")
    print(f"   Total Average Latency: {total_avg_time:.3f}ms")
    print()
    
    # Sort by contribution
    sorted_phases = sorted(phases.items(), key=lambda x: x[1], reverse=True)
    
    for i, (phase, time_ms) in enumerate(sorted_phases, 1):
        percentage = (time_ms / total_avg_time) * 100 if total_avg_time > 0 else 0
        print(f"   {i}. {phase}: {time_ms:.3f}ms ({percentage:.1f}%)")
    
    # Identify primary bottleneck
    primary_bottleneck = sorted_phases[0][0] if sorted_phases else "Unknown"
    primary_percentage = (sorted_phases[0][1] / total_avg_time) * 100 if sorted_phases and total_avg_time > 0 else 0
    
    print(f"\n🎯 PRIMARY BOTTLENECK: {primary_bottleneck}")
    print(f"   Contributes {primary_percentage:.1f}% of total latency")
    
    if primary_bottleneck == "Mempool Residence":
        print(f"   💡 OPTIMIZATION: Focus on private mempool integration")
    elif primary_bottleneck == "Internal Queue":
        print(f"   💡 OPTIMIZATION: Increase processing parallelism")
    elif primary_bottleneck == "REVM Simulation":
        print(f"   💡 OPTIMIZATION: Optimize EVM simulation parameters")
    else:
        print(f"   💡 OPTIMIZATION: Optimize {primary_bottleneck.lower()} implementation")

def generate_timing_report(df, output_dir="./reports"):
    """
    Generate comprehensive timing analysis report with visualizations.
    """
    Path(output_dir).mkdir(exist_ok=True)
    
    print(f"\n" + "="*80)
    print("GENERATING COMPREHENSIVE TIMING REPORT")
    print("="*80)
    
    # Create timing distribution plots
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    fig.suptitle('Transaction Timing Analysis - All Phases', fontsize=16, fontweight='bold')
    
    timing_columns = [
        ('mempool_residence_time_us', 'Mempool Residence Time'),
        ('internal_queue_time_us', 'Internal Queue Time'),
        ('pool_check_time_us', 'Pool Check Time'),
        ('revm_simulation_time_us', 'REVM Simulation Time'),
        ('state_analysis_time_us', 'State Analysis Time'),
        ('end_to_end_time_us', 'End-to-End Time')
    ]
    
    for i, (col, title) in enumerate(timing_columns):
        row, col_idx = i // 3, i % 3
        ax = axes[row, col_idx]
        
        if col in df.columns:
            # Convert to milliseconds and filter outliers for visualization
            data_ms = df[col] / 1000.0
            data_filtered = data_ms[data_ms <= data_ms.quantile(0.99)]  # Remove top 1% outliers
            
            ax.hist(data_filtered, bins=50, alpha=0.7, edgecolor='black')
            ax.set_xlabel('Time (ms)')
            ax.set_ylabel('Frequency')
            ax.set_title(f'{title}\nMean: {data_ms.mean():.2f}ms')
            ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    report_path = Path(output_dir) / 'transaction_timing_analysis.png'
    plt.savefig(report_path, dpi=300, bbox_inches='tight')
    print(f"📊 Timing distribution plots saved to: {report_path}")
    
    # Generate summary statistics CSV
    summary_stats = {}
    for col, title in timing_columns:
        if col in df.columns:
            data_ms = df[col] / 1000.0
            summary_stats[title] = {
                'Mean (ms)': data_ms.mean(),
                'Median (ms)': data_ms.median(),
                'P95 (ms)': data_ms.quantile(0.95),
                'P99 (ms)': data_ms.quantile(0.99),
                'Max (ms)': data_ms.max(),
                'StdDev (ms)': data_ms.std(),
                'Count': len(data_ms[data_ms > 0])
            }
    
    summary_df = pd.DataFrame(summary_stats).T
    summary_path = Path(output_dir) / 'timing_summary_statistics.csv'
    summary_df.to_csv(summary_path)
    print(f"📈 Summary statistics saved to: {summary_path}")
    
    plt.show()

def main():
    """
    Main analysis function - processes transaction timing data and generates reports.
    """
    print("🚀 TRANSACTION TIMING ANALYSIS SYSTEM")
    print("="*80)
    print("OBJECTIVE: Analyze complete transaction processing pipeline timing")
    print("CODE REFERENCE: rust/mempool_processor/src/bin/scam_detection_service.rs")
    print("="*80)
    
    # Look for timing data files
    possible_paths = [
        "../../logs/transaction_timing.csv",
        "../logs/transaction_timing.csv", 
        "./logs/transaction_timing.csv",
        "/home/nima/code/crypto/logs/transaction_timing.csv"
    ]
    
    df = None
    for path in possible_paths:
        if Path(path).exists():
            df = load_timing_data(path)
            if df is not None:
                break
    
    if df is None:
        print("\n❌ No timing data found. Please ensure:")
        print("   1. Rust scam detection service is running")
        print("   2. Transaction timing logs are being generated")
        print("   3. CSV file exists in logs/ directory")
        return
    
    # Perform comprehensive timing analysis
    timing_results = analyze_timing_phases(df)
    analyze_transaction_categories(df)
    analyze_bottlenecks(df)
    
    # Generate detailed report
    generate_timing_report(df)
    
    print(f"\n✅ ANALYSIS COMPLETE")
    print(f"   Processed {len(df):,} transactions")
    print(f"   Generated comprehensive timing breakdown")
    print(f"   Identified bottlenecks and optimization opportunities")

if __name__ == "__main__":
    main() 