use super::super::data_models::receipt_models::*;

/// Enum for decoded events
#[derive(Debug, Clone)]
pub enum DecodedEvent {
    ERC20TransferEvent(ERC20TransferEvent),
    ERC721TransferEvent(ERC721TransferEvent),
    ERC1155TransferEvent(ERC1155TransferEvent),
    ERC20ApprovalEvent(ERC20ApprovalEvent),
    ERC721ApprovalEvent(ERC721ApprovalEvent),
    ApprovalForAllEvent(ApprovalForAllEvent),
    UniswapV2SyncEvent(UniswapV2SyncEvent),
    UniswapV2SwapEvent(UniswapV2SwapEvent),
    UniswapV2MintEvent(UniswapV2MintEvent),
    UniswapV2BurnEvent(UniswapV2BurnEvent),
    UniswapV2PairCreatedEvent(UniswapV2PairCreatedEvent),
    UniswapV3SwapEvent(UniswapV3SwapEvent),
    UniswapV3MintEvent(UniswapV3MintEvent),
    UniswapV3BurnEvent(UniswapV3BurnEvent),
    UniswapV3PoolCreatedEvent(UniswapV3PoolCreatedEvent),
    UniswapV3InitializeEvent(UniswapV3InitializeEvent),
    UniswapV3PositionEvent(UniswapV3PositionEvent),
    UniswapV3IncreaseLiquidityEvent(UniswapV3IncreaseLiquidityEvent),
    UniswapV3DecreaseLiquidityEvent(UniswapV3DecreaseLiquidityEvent),
    UniswapV3CollectEvent(UniswapV3CollectEvent),
    UniswapV4SwapEvent(UniswapV4SwapEvent),
    UniswapV4InitializeEvent(UniswapV4InitializeEvent),
    UniswapV4ModifyLiquidityEvent(UniswapV4ModifyLiquidityEvent),
    UniswapV4DonateEvent(UniswapV4DonateEvent),
    UniswapV4FeeUpdatedEvent(UniswapV4FeeUpdatedEvent),
    UniswapV4DynamicLPFeeUpdatedEvent(UniswapV4DynamicLPFeeUpdatedEvent),
    UniswapV4FeeControllerUpdatedEvent(UniswapV4FeeControllerUpdatedEvent),
    UniswapV4BalanceDeltaEvent(UniswapV4BalanceDeltaEvent),
    DepositEvent(DepositEvent),
    WithdrawEvent(WithdrawEvent),
    OwnershipTransferredEvent(OwnershipTransferredEvent),
    OwnershipTransferStartedEvent(OwnershipTransferStartedEvent),
    AccessControlRoleGrantedEvent(AccessControlRoleGrantedEvent),
    AccessControlRoleRevokedEvent(AccessControlRoleRevokedEvent),
    ProxyAdminChangedEvent(ProxyAdminChangedEvent),
    TradingEnabledEvent(TradingEnabledEvent),
    TradingDisabledEvent(TradingDisabledEvent),
    Permit2Event(Permit2Event),
}
